# Site settings
title: Adam Ellsworth
email: azellsworth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A mishmash minagerie
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://azellsworth.github.io/" # the base hostname & protocol for your site
twitter_username: none
github_username:  azellsworth

# Build settings
markdown: kramdown
